#!/bin/bash

chmod +x shell shellc up
cp shell shellc up /usr/local/bin/
sudo apt-get install xclip

sudo apt install seclists wfuzz gobuster feroxbuster ffuf
gunzip /usr/share/wordlists/rockyou.txt.gz
sudo updatedb.plocate
