#!/bin/bash

chmod +x shell shellc up
cp shell shellc up /usr/local/bin/
sudo apt-get install xclip

sudo apt install seclists wfuzz gobuster feroxbuster ffuf
gunzip /usr/share/wordlists/rockyou.txt.gz
sudo updatedb.plocate
mkdir /home/me/thm /home/me/htb
rm -rf /home/me/Music /home/me/Public /home/me/Templates /home/me/Videos
