#!/bin/bash

# Install:
# chmod +x up
# sudo cp up /usr/local/sbin
# execute using `up`

GREEN='\033[0;32m'
NC='\033[0m' # No color

interface=tun0
port=80
ip=$(/sbin/ip -o -4 addr list $interface | awk '{print $4}' | cut -d/ -f1)
echo -e "Running on ${GREEN}$ip${NC}"
python3 -m http.server $port
